import type { Metadata } from "next";
import "@/styles/article-content.css";
import { SITE_NAME, SITE_URL } from "@/lib/seo";

const title = "Privacy Policy";
const description =
  "Comprehensive privacy policy for Bloxodes.com covering analytics, advertising, cookies/local storage, and your data rights.";
const canonical = `${SITE_URL.replace(/\/$/, "")}/privacy-policy`;
const ogImage = `${SITE_URL}/og-image.png`;

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical },
  openGraph: {
    type: "website",
    url: canonical,
    title,
    description,
    siteName: SITE_NAME,
    images: [ogImage]
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [ogImage]
  }
};

export default function PrivacyPolicyPage() {
  const structuredData = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "PrivacyPolicy",
    name: title,
    description,
    url: canonical,
    publisher: {
      "@type": "Organization",
      name: SITE_NAME,
      url: SITE_URL
    }
  });

  return (
    <div className="grid gap-8 lg:grid-cols-[minmax(0,3fr)_minmax(0,1.25fr)]">
      <article className="prose dark:prose-invert max-w-none game-copy space-y-10">
        <header className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">{title}</h1>
          <p className="text-base text-muted sm:text-lg">{description}</p>
        </header>

        <section className="space-y-4">
          <p>
            <strong>Effective Date:</strong> October 3, 2025
            <br />
            <strong>Last Updated:</strong> December 8, 2025
          </p>
          <p>
            Bloxodes.com ("Bloxodes," "we," "our," or "us") publishes Roblox code guides and related articles. We designed this site to
            work without user accounts, comments, or newsletters. We do not ask you to register and we do not collect your name, password,
            or similar profile information.
          </p>
          <p>
            This Privacy Policy explains what we do collect (mostly technical data generated by your browser), how we use it, and the
            choices you have. We wrote this in line with global privacy laws: including the EU/UK GDPR, the ePrivacy rules on cookies, the
            California CCPA/CPRA, the U.S. state privacy laws (VA/CO/CT/UT, etc.), India’s DPDP Act 2023, and COPPA for children’s
            privacy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">1) What We Collect (and What We Don’t)</h2>
          <div className="space-y-3">
            <div>
              <p className="font-medium">We do not:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Run user registrations, comments, forums, or newsletters.</li>
                <li>Collect your name, postal address, phone number, or passwords.</li>
              </ul>
            </div>
            <div>
              <p className="font-medium">We may collect automatically (standard web/ads/analytics data):</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  Network and device data your browser sends when loading pages: IP address, user-agent, referral URL, timestamps, pages
                  viewed, and basic device/OS/browser details.
                </li>
                <li>
                  Cookie or local-storage identifiers created by our analytics and advertising partners (see Sections 2–4). We do not set
                  tracking cookies of our own beyond basic site preferences.
                </li>
              </ul>
            </div>
            <p>
              <strong>If you contact us by email:</strong> We receive your email address and the content of your message solely to respond.
              We do not add you to any mailing list.
            </p>
            <p>
              <strong>Checklists &amp; Tools:</strong> If you use our game checklists or in-browser tools, your completion status (checked
              items, progress, preferences) is stored locally in your browser using local storage so your checklist stays saved on the same
              device. This data does not leave your browser unless you clear storage or move to a new device. We do not read or collect this
              data on our servers.
            </p>
            <p>We do not provide any public or user-accessible admin panel on Bloxodes.com.</p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">2) Analytics</h2>
          <p>
            We use Google Analytics 4 (GA4) to understand aggregated site usage (which pages are most read, approximate geographies, device
            types). GA4 uses cookies or similar technologies to generate anonymous measurement. We do not combine GA4 data with information
            that directly identifies you.
          </p>
          <p>
            In regions where GDPR/ePrivacy applies (EEA/UK/CH), we request consent before using analytics cookies and similar technologies
            where required by law.
          </p>
          <p>
            We also use Vercel Analytics and Speed Insights to measure site performance and basic usage metrics (page views, device type,
            performance timings). These tools collect only aggregated and anonymized technical data without setting tracking cookies or
            storing personal identifiers. This information helps us understand site performance and improve loading speeds.
          </p>
          <p>
            Your choices: install Google’s opt-out browser add-on, use your browser’s tracking protection, or block analytics scripts in your
            settings/extensions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">3) Advertising</h2>
          <p>
            We use Google AdSense so we can offer content for free. AdSense places advertising code that may read/write cookies or similar
            identifiers and uses your device/network information to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Deliver and measure ads</li>
            <li>Limit how often you see an ad</li>
            <li>Detect fraud and abuse</li>
          </ul>
          <p>
            <strong>Third-Party Disclosure (required wording):</strong> Third parties, including Google, may use cookies or device
            identifiers to serve ads, measure traffic, and detect fraud. You can learn how Google uses data here:
            <br />
            <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">
              https://policies.google.com/technologies/partner-sites
            </a>
          </p>
          <p>
            In regions where consent is legally required (e.g., EEA/UK/CH), we will request consent before using advertising/measurement
            cookies. If consent is not provided, Google will serve only non-personalized/contextual ads that do not use cookies for
            targeting. You can withdraw consent at any time through the cookie banner.
          </p>
          <p>
            You can manage Google ad preferences at:
            <br />
            <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer">
              https://www.google.com/settings/ads
            </a>
          </p>
          <p>
            We do not directly sell your personal information. Under some U.S. state laws, participation in interest-based advertising can
            be considered a "share" of personal information with ad partners. See Section 9 for your opt-out rights.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">4) Cookies &amp; Local Storage</h2>
          <p>
            <strong>Essential site preferences:</strong> We store a simple theme preference (light/dark) in your browser’s local storage so
            the site looks the same on your next visit. This is not used to track you across sites.
          </p>
          <p>
            <strong>Checklist progress:</strong> When you use our checklists, your progress is stored in local storage so your progress stays
            saved on your device. This information remains in your browser only and is not sent to our servers.
          </p>
          <p>
            <strong>Analytics/Ads cookies:</strong> Set by Google Analytics and Google AdSense. These help measure traffic, deliver/measure
            ads, and protect against fraud.
          </p>
          <p>
            You can block or delete cookies via your browser settings. If you block non-essential cookies, some analytics and ad features may
            be limited.
          </p>
          <p>
            To minimize repeated prompts, we store your cookie consent preference so we do not ask again on every visit. You can change this
            preference any time through the cookie banner.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">5) Legal Bases for Processing (GDPR/UK GDPR)</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Consent:</strong> for analytics and advertising cookies where required by law.
            </li>
            <li>
              <strong>Legitimate interests:</strong> to keep the site secure (fraud/abuse prevention), operate the service, and understand
              high-level content performance in a privacy-respecting way.
            </li>
            <li>
              <strong>Legal obligations:</strong> to comply with applicable laws, regulatory requests, or enforce our terms.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">6) Data Sharing</h2>
          <p>We do not sell your personal information. We share data only with service providers that help us run the site:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Google (Analytics/AdSense):</strong> acts as an independent controller for analytics and advertising.
            </li>
            <li>
              <strong>Vercel (hosting and edge delivery):</strong> provides secure website hosting and logging.
            </li>
          </ul>
          <p>
            We may also disclose information if required by law or to protect the security of our users and our service. If we undergo a
            business change (e.g., acquisition), we will provide notice before your data becomes subject to a different policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">7) International Transfers</h2>
          <p>
            Our providers may process data in multiple countries (e.g., U.S., EU). Where applicable, they rely on safeguards like Standard
            Contractual Clauses or other lawful transfer mechanisms. We choose established vendors with strong security and compliance
            programs.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">8) Retention</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Server/hosting logs (Vercel):</strong> kept for operational security and troubleshooting and deleted on a schedule
              determined by our host.
            </li>
            <li>
              <strong>Analytics data (GA4):</strong> retained according to GA4’s configurable retention windows. We keep aggregated
              analytics as long as needed to improve the site.
            </li>
            <li>
              <strong>User emails:</strong> retained only as long as needed to respond and maintain reasonable business records.
            </li>
          </ul>
          <p>When retention periods expire or data is no longer needed, we delete or de-identify it.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">9) Your Rights &amp; Choices</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>EEA/UK/Switzerland:</strong> access, correction, deletion, restriction, portability, withdraw consent, object to
              processing.
            </li>
            <li>
              <strong>California &amp; other U.S. states:</strong> access or delete personal information; request to know; opt out of
              "sharing" by using Google’s ad preference tools and emailing us.
            </li>
            <li>
              <strong>India:</strong> access/correction, grievance redressal, deletion.
            </li>
          </ul>
          <p>
            To exercise any right, email <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a>
            <br />. We may ask you to confirm information to verify your request.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">10) Children’s Privacy (COPPA)</h2>
          <p>
            Bloxodes is intended for players aged 13 and above.
            <br />
            We do not knowingly collect personal information from children under 13 (or a higher minimum age where required). If you believe
            a child provided personal information to us, please email <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a> and
            we will promptly delete it.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">11) Security</h2>
          <p>
            We use HTTPS across the site, rely on reputable cloud providers with strong security practices (Vercel, Google), limit admin
            access, and review our configuration to reduce risk. No online service can guarantee absolute security, but we work to protect
            your information against unauthorized access, alteration, and misuse.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">12) Third-Party Links</h2>
          <p>
            Our pages may link to third-party sites (e.g., Roblox, X/Twitter, Discord, Telegram). Those sites have their own privacy
            practices. Review their policies before submitting information.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">13) Changes to This Policy</h2>
          <p>We will update this page when our data practices or legal requirements change. The “Last Updated” date shows the latest revision.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">14) Bloxodes Chrome Extension</h2>
          <p>
            Privacy Policy for Bloxodes Extension: The Bloxodes Chrome Extension does not collect, store, or share any personal data from
            users. It only retrieves publicly available Roblox game data and displays active game codes directly on Roblox game pages. No
            analytics, tracking, or cookies are used.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">15) Contact</h2>
          <p>
            <strong>Email:</strong> <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a>
            <br />
            <strong>Website:</strong>{" "}
            <a href="https://bloxodes.com" target="_blank" rel="noopener noreferrer">
              https://bloxodes.com
            </a>
          </p>
          <p>If you have privacy questions or want to exercise your rights, write to us and we’ll respond promptly.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">Plain-English Summary</h2>
          <p>
            We don’t run accounts, comments, or newsletters. We measure traffic (GA4) and show ads (AdSense). Those services may place
            cookies or similar tech. In the EU/UK/CH, we ask for cookie consent before using analytics/ads cookies. You can control cookies
            in your browser and use Google’s opt-out tools. Checklist progress is stored locally in your browser and never sent to us. If you
            email us, we only use your address to reply.
          </p>
        </section>

        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} />
      </article>

      <aside aria-hidden className="hidden lg:block" />
    </div>
  );
}
