import type { Metadata } from "next";
import "@/styles/article-content.css";
import { SITE_NAME, SITE_URL } from "@/lib/seo";

const title = "Privacy Policy";
const description = "Comprehensive privacy policy for Bloxodes.com covering analytics, advertising, and your data rights.";
const canonical = `${SITE_URL.replace(/\/$/, "")}/privacy-policy`;
const ogImage = `${SITE_URL}/og-image.png`;

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical },
  openGraph: {
    type: "website",
    url: canonical,
    title,
    description,
    siteName: SITE_NAME,
    images: [ogImage]
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [ogImage]
  }
};

export default function PrivacyPolicyPage() {
  const structuredData = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "PrivacyPolicy",
    name: title,
    description,
    url: canonical,
    publisher: {
      "@type": "Organization",
      name: SITE_NAME,
      url: SITE_URL
    }
  });

  return (
    <div className="grid gap-8 lg:grid-cols-[minmax(0,3fr)_minmax(0,1.25fr)]">
      <article className="prose dark:prose-invert max-w-none game-copy space-y-10">
        <header className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">{title}</h1>
          <p className="text-base text-muted sm:text-lg">{description}</p>
        </header>

        <section className="space-y-4">
          <p>
            <strong>Effective Date:</strong> October 3, 2025
            <br />
            <strong>Last Updated:</strong> October 3, 2025
          </p>
          <p>
            Bloxodes.com ("Bloxodes," "we," "our," or "us") publishes Roblox code guides and related articles. We designed this
            site to work without user accounts, comments, or newsletters. We do not ask you to register and we do not collect your
            name, password, or similar profile information.
          </p>
          <p>
            This Privacy Policy explains what we do collect (mostly technical data generated by your browser), how we use it, and the
            choices you have. We wrote this in line with global privacy laws—including the EU/UK GDPR, the ePrivacy rules on cookies,
            the California CCPA/CPRA, the U.S. state privacy laws (VA/CO/CT/UT, etc.), India’s DPDP Act 2023, and COPPA for children’s
            privacy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">1) What We Collect (and What We Don’t)</h2>
          <div>
            <div>
              <p className="font-medium">We do not:</p>
              <ul className="list-disc pl-6">
                <li>Run user registrations, comments, forums, or newsletters.</li>
                <li>Collect your name, postal address, phone number, or passwords.</li>
              </ul>
            </div>
            <div>
              <p className="font-medium">We may collect automatically (standard web/ads/analytics data):</p>
              <ul className="list-disc pl-6">
                <li>
                  Network and device data your browser sends when loading pages: IP address, user-agent, referral URL, time stamps,
                  pages viewed, and basic device/OS/browser details.
                </li>
                <li>
                  Cookie or local-storage identifiers created by our analytics and advertising partners (see Sections 2–3). We do not
                  set tracking cookies of our own beyond basic site preferences (e.g., theme).
                </li>
              </ul>
            </div>
            <p>
              <strong>If you contact us by email:</strong> We receive your email address and the content of your message solely to
              respond. We do not add you to any mailing list.
            </p>
            <p>
              <strong>Admin-only area:</strong> We use Supabase authentication only for our internal admin route (/admin). Regular
              visitors never interact with or need this feature.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">2) Analytics</h2>
          <p>
            We use Google Analytics 4 (GA4) to understand aggregated site usage (which pages are most read, approximate geographies,
            device types). GA4 uses cookies or similar technologies to generate anonymous measurement. We do not combine GA4 data with
            information that directly identifies you.
          </p>
          <p>
            <strong>Your choices:</strong> install Google’s{' '}
            <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">
              opt-out browser add-on
            </a>
            , use your browser’s tracking protection, or block analytics scripts in your settings/extensions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">3) Advertising</h2>
          <p>
            We use Google AdSense (including Auto Ads) so we can offer content for free. AdSense places advertising code that may
            read/write cookies or similar identifiers and uses your device/network information to:
          </p>
          <ul className="list-disc pl-6">
            <li>Deliver and measure ads;</li>
            <li>Limit how often you see an ad;</li>
            <li>Detect fraud and abuse.</li>
          </ul>
          <p>
            In regions where consent is legally required (e.g., EEA/UK/CH), we will request consent before using
            advertising/measurement cookies to the extent the law requires. If consent is not provided, we will limit advertising
            features where feasible and prioritize non-personalized/contextual ads. You can also manage Google ad preferences at{' '}
            <a href="https://adssettings.google.com" target="_blank" rel="noopener noreferrer">
              adssettings.google.com
            </a>
            .
          </p>
          <p>
            We do not directly sell your personal information. Under some U.S. state laws, participation in interest-based advertising
            can be considered a "share" of personal information with ad partners. See Section 9 for your opt-out rights.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">4) Cookies &amp; Local Storage</h2>
          <ul className="list-disc pl-6">
            <li>
              <strong>Essential site preferences:</strong> We store a simple theme preference (light/dark) in your browser’s local
              storage so the site looks the same on your next visit. This is not used to track you across sites.
            </li>
            <li>
              <strong>Analytics/Ads cookies:</strong> Set by Google Analytics and Google AdSense. These help measure traffic,
              deliver/measure ads, and protect against fraud.
            </li>
          </ul>
          <p>You can block or delete cookies via your browser settings. If you block non-essential cookies, some analytics and ad features may be limited.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">5) Legal Bases for Processing (GDPR/UK GDPR)</h2>
          <ul className="list-disc pl-6">
            <li>
              <strong>Consent:</strong> for analytics and advertising cookies where required by law.
            </li>
            <li>
              <strong>Legitimate interests:</strong> to keep the site secure (fraud/abuse prevention), operate the service, and understand
              high-level content performance in a privacy-respecting way.
            </li>
            <li>
              <strong>Legal obligations:</strong> to comply with applicable laws, regulatory requests, or enforce our terms.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">6) Data Sharing</h2>
          <p>We do not sell your personal information. We share data only with service providers that help us run the site:</p>
          <ul className="list-disc pl-6">
            <li>
              <strong>Google (Analytics/AdSense):</strong> acts as an independent controller for analytics and advertising.
            </li>
            <li>
              <strong>Netlify (hosting and edge delivery):</strong> provides secure website hosting and logging.
            </li>
            <li>
              <strong>Supabase (database/auth/storage):</strong> powers our internal admin features.
            </li>
          </ul>
          <p>
            We may also disclose information if required by law or to protect the security of our users and our service. If we undergo
            a business change (e.g., acquisition), we will provide notice before your data becomes subject to a different policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">7) International Transfers</h2>
          <p>
            Our providers may process data in multiple countries (e.g., U.S., EU). Where applicable, they rely on safeguards like Standard
            Contractual Clauses or other lawful transfer mechanisms. We choose established vendors with strong security and compliance
            programs.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">8) Retention</h2>
          <ul className="list-disc pl-6">
            <li>
              <strong>Server/hosting logs (Netlify):</strong> kept for operational security and troubleshooting and deleted on a schedule
              determined by our host.
            </li>
            <li>
              <strong>Analytics data (GA4):</strong> retained according to GA4’s configurable retention windows. We keep aggregated
              analytics as long as needed to improve the site.
            </li>
            <li>
              <strong>User emails:</strong> retained only as long as needed to respond and maintain reasonable business records.
            </li>
          </ul>
          <p>When retention periods expire or data is no longer needed, we delete or de-identify it.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">9) Your Rights &amp; Choices</h2>
          <ul className="list-disc pl-6">
            <li>
              <strong>EEA/UK/Switzerland (GDPR/UK GDPR):</strong> Request access, correction, deletion, restriction, portability, or object
              to processing. Withdraw consent at any time. Lodge a complaint with your data protection authority.
            </li>
            <li>
            <strong>California &amp; other U.S. states (CCPA/CPRA, VCDPA, CPA, CTDPA, UCPA, etc.):</strong> Request to know, access, or delete
            personal information. We do not "sell" information for money. Opt out of any "sharing" by using Google’s ad preference tools
            and emailing us.
          </li>
            <li>
              <strong>India (DPDP Act 2023):</strong> Request access/correction, grievance redressal, and deletion consistent with the Act and
              its rules, subject to legal exceptions.
            </li>
          </ul>
          <p>
            To exercise any right, email <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a>. We may ask you to confirm
            information to verify your request.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">10) Children’s Privacy</h2>
          <p>
            Bloxodes is a general-audience site. We do not knowingly collect personal information from children under 13 (or a higher age
            where required). If you believe a child provided personal information to us, please email <a href="mailto:getbloxodes@gmail.com">
              getbloxodes@gmail.com
            </a>{' '}
            and we will promptly delete it.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">11) Security</h2>
          <p>
            We use HTTPS across the site, rely on reputable cloud providers with strong security practices (Netlify, Google, Supabase),
            limit admin access, and review our configuration to reduce risk. No online service can guarantee absolute security, but we work
            to protect your information against unauthorized access, alteration, and misuse.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">12) Third-Party Links</h2>
          <p>
            Our pages may link to third-party sites (e.g., Roblox, X/Twitter, Discord, Telegram). Those sites have their own privacy
            practices. Review their policies before submitting information.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">13) Changes to This Policy</h2>
          <p>We will update this page when our data practices or legal requirements change. The “Last Updated” date shows the latest revision.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">Bloxodes Chrome Extension</h2>
          <p>
            <strong>Privacy Policy for Bloxodes Extension:</strong> The Bloxodes Chrome Extension does not collect, store, or share any personal
            data from users. It only retrieves publicly available Roblox game data and displays active game codes directly on Roblox game pages.
            No analytics, tracking, or cookies are used.
          </p>
          <p>
            For any extension-specific privacy questions, contact us at{" "}
            <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a>.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">14) Contact</h2>
          <p>
            <strong>Email:</strong> <a href="mailto:getbloxodes@gmail.com">getbloxodes@gmail.com</a>
            <br />
            <strong>Website:</strong>{' '}
            <a href="https://bloxodes.com" target="_blank" rel="noopener noreferrer">
              https://bloxodes.com
            </a>
          </p>
          <p>If you have privacy questions or want to exercise your rights, write to us and we’ll respond promptly.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground sm:text-3xl">Plain-English Summary</h2>
          <p>
            We don’t run accounts, comments, or newsletters. We measure traffic (GA4) and show ads (AdSense). Those services may place
            cookies or similar tech. You can control cookies in your browser and use Google’s opt-out tools. If you email us, we only use
            your address to reply. That’s it.
          </p>
        </section>

        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} />
      </article>

      <aside aria-hidden className="hidden lg:block" />
    </div>
  );
}
